### ISSUE TITLE
Integrate into Orion

### ISSUE THREAD

**Issue by gam-ragnar** [froatsnook/meteor-alt#1]
Honored to be the first here :) . What is the possibility of working this into a front-end framework for orionjs https://atmospherejs.com/?q=orion  http://orionjs.org/ Meteor definitely needs an approachable flux implementation and from what I have gather alt is approachable.

**Comment by gam-ragnar** [comment]
I found https://github.com/gaearon/redux simply blown away :) I think it's a better fit for Orion

**Comment by froatsnook** [comment]
Hi @timfam.  Thanks for the interest and for sharing the link!
